### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/mrp-repair-addons#50]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] lost_object
- [ ] mrp_repair_account_invoicing
- [ ] mrp_repair_cancel_reason
- [ ] mrp_repair_customer_lot
- [ ] mrp_repair_date
- [ ] mrp_repair_estimated_cost
- [ ] mrp_repair_estimated_qty
- [ ] mrp_repair_expense
- [ ] mrp_repair_fee
- [ ] mrp_repair_invoice_method
- [ ] mrp_repair_lot
- [ ] mrp_repair_partner_analytic
- [ ] mrp_repair_pricelist_rules
- [ ] mrp_repair_proforma_report
